username = input('Введите имя пользователя: ')
first_title = input('Введите первый заголовок: ')
second_title = input('Введите второй заголовок: ')
third_title = input('Ввелите третий заголовок: ')
titles = []
titles.append(first_title)
titles.append(second_title)
titles.append(third_title)
content = input('Введите текст заметки: ')
status  = input('Введите в качестве статуса заметки "активна" или "не активна": ')
created_date = input('Введите дату создания в формате дд.мм.гггг: ')
issue_date = input('Введите дату истечения заметки в формате дд.мм.гггг: ')

print("Имя пользователя:", username)
print("Заголовки заметки:", titles)
print("Описание заметки:", content)
print("Статус заметки:", status)
print("Дата создания заметки:", created_date)
print("Дата истечения заметки:", issue_date)